version: "3"

volumes:
  history-postgres-data:
    driver: local

services:
  #
  # HISTORY SERVICE
  #
  history-postgres:
    container_name: history-postgres
    image: postgres
    volumes:
      - history-postgres-data:/var/lib/postgresql/data
  history-api:
    container_name: history-api
    build: .
    ports:
      - 5040:5040
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@history-postgres:5432/postgres?sslmode=disable
      - PORT=5040
    depends_on:
      - history-postgres
    links:
      - history-postgres
